In [2]:
import numpy as np 
data1= [6,7,8,9,0,1]
a1= np.array(data1)
print(a1)
print("Type:",type(a1))

[6 7 8 9 0 1]
Type: <class 'numpy.ndarray'>


In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original Array:\n", arr)


row_slice = arr[0, :]  

col_slice = arr[:, 1]


submatrix = arr[1:3, 2:4]

print("\nFirst Row:", row_slice)
print("Second Column:", col_slice)
print("Submatrix:\n", submatrix)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First Row: [1 2 3 4]
Second Column: [ 2  6 10]
Submatrix:
 [[ 7  8]
 [11 12]]


In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

sliced_arr = arr[::2, ::2]

print("Sliced Array with Steps:\n", sliced_arr)

Sliced Array with Steps:
 [[ 1  3]
 [ 9 11]]


In [5]:
arr_3 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [1., 3., 5.]])
arr_tranp = arr_3.transpose()
print("Original matrix:\n", arr_3)
print("Transpose matrix:\n", arr_tranp)

Original matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 3. 5.]]
Transpose matrix:
 [[1. 4. 7. 1.]
 [2. 5. 8. 3.]
 [3. 6. 9. 5.]]


In [6]:
arr_3.T
arr_3.T.shape
arr_3.shape

(4, 3)

In [7]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print("Element-wise addition:\n", arr + 2)
print("Element-wise multiplication:\n", arr * 2)
print("Element-wise exponentiation:\n", arr ** 2)
print("Comparison:\n", arr2 > arr)

Element-wise addition:
 [[3. 4. 5.]
 [6. 7. 8.]]
Element-wise multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]]
Element-wise exponentiation:
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Comparison:
 [[False  True False]
 [ True False  True]]
